# hai kawan....
# jadi disini kita akan menjalankan perintah untuk output text...
# dengan mengetik berikut...

print("Helloooooooooooooooooooo dunia")

# udah deh gitu aja 
# gampang kan...............